# module_permissions.py
# NEXO / ZYRA — LOGÍSTICA ASIA
# PERMISOS DEL MÓDULO
# PASIVO | CONSULTADO POR CORE

MODULE_PERMISSIONS = {
    "SHIPMENT_CREATE": ["OPERADOR", "ADMIN_EMPRESA"],
    "SHIPMENT_UPDATE": ["OPERADOR", "ADMIN_EMPRESA"],
    "CUSTOMS_UPDATE": ["ADMIN_EMPRESA", "CONTADOR"],
    "DELIVERY_CONFIRM": ["OPERADOR"],
    "VIEW_LOGISTICS": ["OPERADOR", "ADMIN_EMPRESA", "PROPIETARIO_EMPRESA"]
}